baseurl = "https://rafaeljesus.dev.br"
title = "Rafael Jesus"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Rafael Jesus"
  info = "Desenvolvedor de Software | Entusiasta de Tecnologia"
  description = "Bem-vindo ao meu blog pessoal, onde compartilho ideias e projetos."
  keywords = "blog,developer,projetos"
  avatarURL = "/images/rafaeljesus.jpg"
  #gravatar = "rafael.j.oliveira.s2@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon_32.svg"
  favicon_16 = "/img/favicon.svg"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/B4bayaga"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/rafael-jesus-75935b106/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/rafarafael83"
  [[params.social]]
  name = "Reddit"
  icon = "fa-brands fa-reddit fa-2x"
  weight = 3
  url = "https://www.reddit.com/?feed=home"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projetos"
  weight = 2
  url = "projetos/"
[[menu.main]]
  name = "Sobre"
  weight = 3
  url = "sobre/"